pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'